name: Regression

on:
  push:
    tags:
      - 'v*.*.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macOS-latest]
        rust: [stable]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --verbose
    - name: Package for Windows
      if: matrix.os == 'windows-latest'
      run: |
        mkdir release
        mv target/release/voicechanger.dll release/
        zip -9 -r voicechanger-win-x86_64.zip release
    - name: Package for Windows
      if: matrix.os == 'macOS-latest'
      run: |
        mkdir -p release/voicechanger.vst/Contents/MacOS
        mv target/release/libvoicechanger.dylib release/voicechanger.vst/Contents/MacOS/
        zip -9 -r voicechanger-macos-x86_64.zip release
    - name: Create Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        files: '*.zip'
